services:
  front:
    build: ./nuxt/
    container_name: nuxt
    restart: always
    volumes:
    - ./nuxt/webapp:/app
    ports:
    - '3000:3000'
    environment:
      PORT: 3000
      BACKEND_URL: 'http://localhost:4000'
    command: "npm run dev"
  back:
    build: ./nest/
    container_name: nest
    restart: always
    volumes:
      - ./nest/forward-api:/app
    ports:
      - '4000:4000'
      - '81:81'
    environment:
      PORT: 4000
      JWT_SECRET: 'SECRET_TOKEN_!!!'
    command: "npm run start:dev"